/*

AUTOR: GUSTAVO MATHIAS DE SIQUEIRA

DATA: 

DESCRIÇÃO DA CLASSE: 

DATA ULTIMA MODIFICAÇÃO: 


*/
package visao;

import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Gustavo
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

   /**
    * Creates new form FrmMenuCadastros
    */
   public FrmMenuPrincipal() {
      try {
         UIManager.setLookAndFeel(new WindowsLookAndFeel());
      } catch (UnsupportedLookAndFeelException ex) {
         Logger.getLogger(FrmAvaliacaoDeCompra.class.getName()).log(Level.SEVERE, null, ex);
      }

      initComponents();

      verificaHora();
     
   }

   
   
   
   
   
   public void carregaFuncionario() {

   }

   public void verificaHora() {
      Date hora = new Date();

      if (hora.getHours() >= 6 && hora.getHours() < 12) {
         jlMensagem.setText("Bom Dia!");
      } else if (hora.getHours() >= 12 && hora.getHours() < 18) {
         jlMensagem.setText("Boa Tarde!");
      } else if (hora.getHours() >= 18 || hora.getHours() < 6) {
         jlMensagem.setText("Boa Noite!");
      }

      SimpleDateFormat df = new SimpleDateFormat("dd/MM/YYYY");
      Date data = new Date();

      jlAcesso.setText("Acesso em: " + df.format(data));

   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jMenu1 = new javax.swing.JMenu();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jlAcesso = new javax.swing.JLabel();
      jlMensagem = new javax.swing.JLabel();
      jMenuBar1 = new javax.swing.JMenuBar();
      jMenuClientes = new javax.swing.JMenu();
      jMenuItemCadastroCliente = new javax.swing.JMenuItem();
      jMenuItemHistoricoCompraCliente = new javax.swing.JMenuItem();
      jMenuItemDebitosCliente = new javax.swing.JMenuItem();
      jMenuItemGerarCartaoFidelidade = new javax.swing.JMenuItem();
      jMenuCompras = new javax.swing.JMenu();
      jMenuItemRealaizarCompra = new javax.swing.JMenuItem();
      jMenuItemAvaliarCompra = new javax.swing.JMenuItem();
      jMenuItemReceberCompra = new javax.swing.JMenuItem();
      jMenuItemConsultarRecebimento = new javax.swing.JMenuItem();
      jMenuItemReabrirRecebimento = new javax.swing.JMenuItem();
      jMenuItemHistoricoCompraItem = new javax.swing.JMenuItem();
      jMenuItemHistoricoCompraFornecedor = new javax.swing.JMenuItem();
      jMenuVendas = new javax.swing.JMenu();
      jMenuItemRealizarVenda = new javax.swing.JMenuItem();
      jMenuItemEstornoVenda = new javax.swing.JMenuItem();
      jMenuMaterial = new javax.swing.JMenu();
      jMenuItemProduto = new javax.swing.JMenuItem();
      jMenuItemGrupoProduto = new javax.swing.JMenuItem();
      jMenuItemSubGrupoProduto = new javax.swing.JMenuItem();
      jMenuItemFornecedor = new javax.swing.JMenuItem();
      jMenuItemMovimentoEstoque = new javax.swing.JMenuItem();
      jMenuRH = new javax.swing.JMenu();
      jMenuItemFuncionario = new javax.swing.JMenuItem();
      jMenuItemFolhaPagamento = new javax.swing.JMenuItem();
      jMenuRelatorios = new javax.swing.JMenu();
      jMenuFinanceiro = new javax.swing.JMenu();
      jMenuItemDuplicatas = new javax.swing.JMenuItem();
      jMenuItemHistoricoPagamentos = new javax.swing.JMenuItem();
      jMenuItemIncluirContaMensal = new javax.swing.JMenuItem();

      jMenu1.setText("jMenu1");

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Menu Principal");
      setBackground(new java.awt.Color(255, 255, 255));
      setResizable(false);

      jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagemSistema/java.png"))); // NOI18N

      jLabel2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
      jLabel2.setText("usuario");

      jlAcesso.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
      jlAcesso.setText("data acesso");

      jlMensagem.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
      jlMensagem.setText("mensagem");

      jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
      jMenuBar1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
      jMenuBar1.setPreferredSize(new java.awt.Dimension(153, 30));

      jMenuClientes.setText("Clientes");
      jMenuClientes.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
      jMenuClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jMenuClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      jMenuClientes.setPreferredSize(new java.awt.Dimension(90, 25));
      jMenuClientes.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuClientesActionPerformed(evt);
         }
      });

      jMenuItemCadastroCliente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
      jMenuItemCadastroCliente.setText("Cadastro de Cliente");
      jMenuItemCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemCadastroClienteActionPerformed(evt);
         }
      });
      jMenuClientes.add(jMenuItemCadastroCliente);

      jMenuItemHistoricoCompraCliente.setText("Histórico Compras do Cliente");
      jMenuItemHistoricoCompraCliente.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemHistoricoCompraClienteActionPerformed(evt);
         }
      });
      jMenuClientes.add(jMenuItemHistoricoCompraCliente);

      jMenuItemDebitosCliente.setText("Débitos do Cliente");
      jMenuClientes.add(jMenuItemDebitosCliente);

      jMenuItemGerarCartaoFidelidade.setText("Geração de Cartão Fidelidade");
      jMenuItemGerarCartaoFidelidade.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemGerarCartaoFidelidadeActionPerformed(evt);
         }
      });
      jMenuClientes.add(jMenuItemGerarCartaoFidelidade);

      jMenuBar1.add(jMenuClientes);

      jMenuCompras.setText("Compras");
      jMenuCompras.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
      jMenuCompras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jMenuCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      jMenuCompras.setPreferredSize(new java.awt.Dimension(100, 25));
      jMenuCompras.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuComprasActionPerformed(evt);
         }
      });

      jMenuItemRealaizarCompra.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
      jMenuItemRealaizarCompra.setText("Realizar Compra");
      jMenuItemRealaizarCompra.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemRealaizarCompraActionPerformed(evt);
         }
      });
      jMenuCompras.add(jMenuItemRealaizarCompra);

      jMenuItemAvaliarCompra.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
      jMenuItemAvaliarCompra.setText("Avaliar Compra");
      jMenuItemAvaliarCompra.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemAvaliarCompraActionPerformed(evt);
         }
      });
      jMenuCompras.add(jMenuItemAvaliarCompra);

      jMenuItemReceberCompra.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
      jMenuItemReceberCompra.setText("Receber Compra");
      jMenuItemReceberCompra.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemReceberCompraActionPerformed(evt);
         }
      });
      jMenuCompras.add(jMenuItemReceberCompra);

      jMenuItemConsultarRecebimento.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
      jMenuItemConsultarRecebimento.setText("Consultar Recebimento");
      jMenuItemConsultarRecebimento.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemConsultarRecebimentoActionPerformed(evt);
         }
      });
      jMenuCompras.add(jMenuItemConsultarRecebimento);

      jMenuItemReabrirRecebimento.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
      jMenuItemReabrirRecebimento.setText("Reabrir Recebimento");
      jMenuItemReabrirRecebimento.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemReabrirRecebimentoActionPerformed(evt);
         }
      });
      jMenuCompras.add(jMenuItemReabrirRecebimento);

      jMenuItemHistoricoCompraItem.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
      jMenuItemHistoricoCompraItem.setText("Histórico Compra Item");
      jMenuItemHistoricoCompraItem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemHistoricoCompraItemActionPerformed(evt);
         }
      });
      jMenuCompras.add(jMenuItemHistoricoCompraItem);

      jMenuItemHistoricoCompraFornecedor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
      jMenuItemHistoricoCompraFornecedor.setText("Histórico Compra Fornecedor");
      jMenuItemHistoricoCompraFornecedor.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemHistoricoCompraFornecedorActionPerformed(evt);
         }
      });
      jMenuCompras.add(jMenuItemHistoricoCompraFornecedor);

      jMenuBar1.add(jMenuCompras);

      jMenuVendas.setText("Vendas");
      jMenuVendas.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
      jMenuVendas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jMenuVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      jMenuVendas.setPreferredSize(new java.awt.Dimension(100, 25));

      jMenuItemRealizarVenda.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
      jMenuItemRealizarVenda.setText("Realizar Venda");
      jMenuVendas.add(jMenuItemRealizarVenda);

      jMenuItemEstornoVenda.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
      jMenuItemEstornoVenda.setText("Estornar Venda");
      jMenuVendas.add(jMenuItemEstornoVenda);

      jMenuBar1.add(jMenuVendas);

      jMenuMaterial.setText("Material");
      jMenuMaterial.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
      jMenuMaterial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jMenuMaterial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      jMenuMaterial.setPreferredSize(new java.awt.Dimension(100, 25));

      jMenuItemProduto.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
      jMenuItemProduto.setText("Cadastro de Produto");
      jMenuItemProduto.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemProdutoActionPerformed(evt);
         }
      });
      jMenuMaterial.add(jMenuItemProduto);

      jMenuItemGrupoProduto.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
      jMenuItemGrupoProduto.setText("Cadastro Grupo de Produto");
      jMenuItemGrupoProduto.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemGrupoProdutoActionPerformed(evt);
         }
      });
      jMenuMaterial.add(jMenuItemGrupoProduto);

      jMenuItemSubGrupoProduto.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
      jMenuItemSubGrupoProduto.setText("Cadastro Subgrupo de Produto");
      jMenuItemSubGrupoProduto.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemSubGrupoProdutoActionPerformed(evt);
         }
      });
      jMenuMaterial.add(jMenuItemSubGrupoProduto);

      jMenuItemFornecedor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
      jMenuItemFornecedor.setText("Cadastro de Fornecedor");
      jMenuItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemFornecedorActionPerformed(evt);
         }
      });
      jMenuMaterial.add(jMenuItemFornecedor);

      jMenuItemMovimentoEstoque.setText("Movimentação do estoque");
      jMenuItemMovimentoEstoque.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemMovimentoEstoqueActionPerformed(evt);
         }
      });
      jMenuMaterial.add(jMenuItemMovimentoEstoque);

      jMenuBar1.add(jMenuMaterial);

      jMenuRH.setText("RH");
      jMenuRH.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
      jMenuRH.setPreferredSize(new java.awt.Dimension(40, 25));

      jMenuItemFuncionario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
      jMenuItemFuncionario.setText("Cadastro de Funcionário");
      jMenuItemFuncionario.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemFuncionarioActionPerformed(evt);
         }
      });
      jMenuRH.add(jMenuItemFuncionario);

      jMenuItemFolhaPagamento.setText("Folha de pagamento");
      jMenuRH.add(jMenuItemFolhaPagamento);

      jMenuBar1.add(jMenuRH);

      jMenuRelatorios.setText("Relatórios");
      jMenuRelatorios.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
      jMenuRelatorios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jMenuRelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      jMenuRelatorios.setPreferredSize(new java.awt.Dimension(100, 25));
      jMenuBar1.add(jMenuRelatorios);

      jMenuFinanceiro.setText("Financeiro");

      jMenuItemDuplicatas.setText("Duplicatas");
      jMenuFinanceiro.add(jMenuItemDuplicatas);

      jMenuItemHistoricoPagamentos.setText("Historico de pagamentos");
      jMenuFinanceiro.add(jMenuItemHistoricoPagamentos);

      jMenuItemIncluirContaMensal.setText("Incluir conta mensal");
      jMenuItemIncluirContaMensal.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemIncluirContaMensalActionPerformed(evt);
         }
      });
      jMenuFinanceiro.add(jMenuItemIncluirContaMensal);

      jMenuBar1.add(jMenuFinanceiro);

      setJMenuBar(jMenuBar1);

      org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 417, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(18, 18, 18)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
               .add(jLabel2)
               .add(jlMensagem)
               .add(jlAcesso))
            .addContainerGap(145, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
               .add(jLabel1)
               .add(layout.createSequentialGroup()
                  .add(38, 38, 38)
                  .add(jlMensagem)
                  .add(27, 27, 27)
                  .add(jLabel2)
                  .add(42, 42, 42)
                  .add(jlAcesso)))
            .addContainerGap(55, Short.MAX_VALUE))
      );

      setSize(new java.awt.Dimension(727, 380));
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void jMenuItemFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncionarioActionPerformed
      dispose();
      FrmFuncionario frmFunc = new FrmFuncionario();
      // frmFunc.p
      frmFunc.setVisible(true);
      //  this.setEnabled(!false);
   }//GEN-LAST:event_jMenuItemFuncionarioActionPerformed

   private void jMenuItemCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroClienteActionPerformed
      // this.setEnabled(false);
      dispose();
      FrmCliente frmCliente = new FrmCliente();
      frmCliente.setVisible(true);
      //  this.setEnabled(true);
   }//GEN-LAST:event_jMenuItemCadastroClienteActionPerformed

   private void jMenuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedorActionPerformed
      //  this.setEnabled(false);
      dispose();
      FrmFornecedor frmForn = new FrmFornecedor();
      frmForn.setVisible(true);
      // this.setEnabled(true);
   }//GEN-LAST:event_jMenuItemFornecedorActionPerformed

   private void jMenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoActionPerformed
      //  this.setEnabled(true)
      dispose();
      FrmProduto frmProd = new FrmProduto();
      frmProd.setVisible(true);
   }//GEN-LAST:event_jMenuItemProdutoActionPerformed

   private void jMenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClientesActionPerformed

   }//GEN-LAST:event_jMenuClientesActionPerformed

   private void jMenuItemGrupoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGrupoProdutoActionPerformed
      dispose();
      FrmGrupo frmGrupo = new FrmGrupo();
      frmGrupo.setVisible(true);
   }//GEN-LAST:event_jMenuItemGrupoProdutoActionPerformed

   private void jMenuItemSubGrupoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSubGrupoProdutoActionPerformed
      dispose();
      FrmSubGrupo frmSubgrupo = new FrmSubGrupo();
      frmSubgrupo.setVisible(true);
   }//GEN-LAST:event_jMenuItemSubGrupoProdutoActionPerformed

   private void jMenuItemRealaizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRealaizarCompraActionPerformed
      dispose();
      FrmCompra frm = new FrmCompra();
      frm.setVisible(true);
   }//GEN-LAST:event_jMenuItemRealaizarCompraActionPerformed

   private void jMenuItemAvaliarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAvaliarCompraActionPerformed
      dispose();
      FrmAvaliacaoDeCompra f = new FrmAvaliacaoDeCompra();
      f.setVisible(true);
   }//GEN-LAST:event_jMenuItemAvaliarCompraActionPerformed

   private void jMenuItemReceberCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReceberCompraActionPerformed
      dispose();
      FrmReceberCompra f = new FrmReceberCompra();
      f.setVisible(true);
   }//GEN-LAST:event_jMenuItemReceberCompraActionPerformed

   private void jMenuItemConsultarRecebimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarRecebimentoActionPerformed
      dispose();
      FrmConsultarRecebimento f = new FrmConsultarRecebimento();
      f.setVisible(true);
   }//GEN-LAST:event_jMenuItemConsultarRecebimentoActionPerformed

   private void jMenuComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuComprasActionPerformed
     
   }//GEN-LAST:event_jMenuComprasActionPerformed

   private void jMenuItemHistoricoCompraItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHistoricoCompraItemActionPerformed
      dispose();
      FrmHistoricoItem f = new FrmHistoricoItem();
      f.setVisible(true);
   }//GEN-LAST:event_jMenuItemHistoricoCompraItemActionPerformed

   private void jMenuItemHistoricoCompraFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHistoricoCompraFornecedorActionPerformed
      // TODO add your handling code here:
      dispose();
      FrmHistoricoFornecedor f = new FrmHistoricoFornecedor();
      f.setVisible(true);
   }//GEN-LAST:event_jMenuItemHistoricoCompraFornecedorActionPerformed

   private void jMenuItemReabrirRecebimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReabrirRecebimentoActionPerformed
      dispose();
      FrmReabrirRecebimento f = new FrmReabrirRecebimento();
      f.setVisible(true);
   }//GEN-LAST:event_jMenuItemReabrirRecebimentoActionPerformed

   private void jMenuItemHistoricoCompraClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHistoricoCompraClienteActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jMenuItemHistoricoCompraClienteActionPerformed

   private void jMenuItemGerarCartaoFidelidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerarCartaoFidelidadeActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jMenuItemGerarCartaoFidelidadeActionPerformed

   private void jMenuItemIncluirContaMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIncluirContaMensalActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jMenuItemIncluirContaMensalActionPerformed

   private void jMenuItemMovimentoEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMovimentoEstoqueActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jMenuItemMovimentoEstoqueActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new FrmMenuPrincipal().setVisible(true);
         }
      });
   }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JMenu jMenuClientes;
   private javax.swing.JMenu jMenuCompras;
   private javax.swing.JMenu jMenuFinanceiro;
   private javax.swing.JMenuItem jMenuItemAvaliarCompra;
   private javax.swing.JMenuItem jMenuItemCadastroCliente;
   private javax.swing.JMenuItem jMenuItemConsultarRecebimento;
   private javax.swing.JMenuItem jMenuItemDebitosCliente;
   private javax.swing.JMenuItem jMenuItemDuplicatas;
   private javax.swing.JMenuItem jMenuItemEstornoVenda;
   private javax.swing.JMenuItem jMenuItemFolhaPagamento;
   private javax.swing.JMenuItem jMenuItemFornecedor;
   private javax.swing.JMenuItem jMenuItemFuncionario;
   private javax.swing.JMenuItem jMenuItemGerarCartaoFidelidade;
   private javax.swing.JMenuItem jMenuItemGrupoProduto;
   private javax.swing.JMenuItem jMenuItemHistoricoCompraCliente;
   private javax.swing.JMenuItem jMenuItemHistoricoCompraFornecedor;
   private javax.swing.JMenuItem jMenuItemHistoricoCompraItem;
   private javax.swing.JMenuItem jMenuItemHistoricoPagamentos;
   private javax.swing.JMenuItem jMenuItemIncluirContaMensal;
   private javax.swing.JMenuItem jMenuItemMovimentoEstoque;
   private javax.swing.JMenuItem jMenuItemProduto;
   private javax.swing.JMenuItem jMenuItemReabrirRecebimento;
   private javax.swing.JMenuItem jMenuItemRealaizarCompra;
   private javax.swing.JMenuItem jMenuItemRealizarVenda;
   private javax.swing.JMenuItem jMenuItemReceberCompra;
   private javax.swing.JMenuItem jMenuItemSubGrupoProduto;
   private javax.swing.JMenu jMenuMaterial;
   private javax.swing.JMenu jMenuRH;
   private javax.swing.JMenu jMenuRelatorios;
   private javax.swing.JMenu jMenuVendas;
   private javax.swing.JLabel jlAcesso;
   private javax.swing.JLabel jlMensagem;
   // End of variables declaration//GEN-END:variables
}
