/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import controle.ConexaoBanco;
import controle.ControleSubGrupo;
import controle.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import modelo.ModeloSubGrupo;

/**
 *
 * @author Gustavo
 */
public class FrmSubGrupo extends javax.swing.JFrame {

    ConexaoBanco connSubGrupo = new ConexaoBanco();
    ConexaoBanco connGrupo = new ConexaoBanco();
    ModeloSubGrupo modSubGrupo = new ModeloSubGrupo();
    ControleSubGrupo controle = new ControleSubGrupo();
    
    
   
    public FrmSubGrupo() {
       try {
          UIManager.setLookAndFeel(new WindowsLookAndFeel());
       } catch (UnsupportedLookAndFeelException ex) {
          Logger.getLogger(FrmAvaliacaoDeCompra.class.getName()).log(Level.SEVERE, null, ex);
       }
        initComponents();
        connSubGrupo.conexao();
        connGrupo.conexao();
        jcbGrupo.removeAllItems();
        connGrupo.executaaSQL("SELECT * FROM GRUPO_PRODUTO");
        preencherTabela();
        jfSubGrupo.setDocument(new LimiteCaracter(100));
        
        try{
           connGrupo.rs.first();
           jcbGrupo.addItem("");
           do{
              jcbGrupo.addItem(""+ connGrupo.rs.getString("NOME_GRUPO"));
           } while(connGrupo.rs.next());
        
        } catch(SQLException ex){
             JOptionPane.showMessageDialog(null, "Erro ao preencher comboBox" + ex);
          }
    }
    
    
    public void preencherTabela(){
       
       ArrayList dados = new ArrayList(); 
       
       String [] Colunas = new String[]{"Código", "Grupo" ,  "SubGrupo"};
       
       connSubGrupo.conexao();
       connSubGrupo.executaaSQL("SELECT * FROM SUBGRUPO_PRODUTO S JOIN GRUPO_PRODUTO C ON S.CODIGO_GRUPO = C.CODIGO_GRUPO ORDER BY CODIGO_SUBGRUPO;");
       
       try{
          connSubGrupo.rs.first();
          
          do{
             dados.add(new Object[]{connSubGrupo.rs.getInt("CODIGO_SUBGRUPO"), 
                 connSubGrupo.rs.getString("NOME_GRUPO"), connSubGrupo.rs.getString("NOME_SUBGRUPO") });
          }while(connSubGrupo.rs.next()); 
       } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Erro ao preencher Tabela:\n" + e);
         }
          
       
       ModeloTabela modelo = new ModeloTabela(dados, Colunas);
       
       jtSubGrupo.setModel(modelo);
       jtSubGrupo.getColumnModel().getColumn(0).setPreferredWidth(50);
       jtSubGrupo.getColumnModel().getColumn(0).setResizable(true);
       
       jtSubGrupo.getColumnModel().getColumn(1).setPreferredWidth(50);
       jtSubGrupo.getColumnModel().getColumn(1).setResizable(true);
       
       jtSubGrupo.getColumnModel().getColumn(2).setPreferredWidth(50);
       jtSubGrupo.getColumnModel().getColumn(2).setResizable(true);
       
       jtSubGrupo.getTableHeader().setReorderingAllowed(true);
       jtSubGrupo.setAutoResizeMode(jtSubGrupo.AUTO_RESIZE_ALL_COLUMNS);//tamanho automatico conforme como é o layout
      
       jtSubGrupo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    
    private void limparCampos(){
       jfCodigo.setText(null);
       jfSubGrupo.setText(null);
       jfSubGrupo.setEnabled(false);
       jcbGrupo.setEnabled(false);
       jcbGrupo.setSelectedItem("");
       jbNovo.setEnabled(true);
       jbInserir.setEnabled(false);
       jbAlterar.setEnabled(false);
       jbExcluir.setEnabled(false);
       jblimparCampos.setEnabled(false);
    
    }
    
    private void habilitarCampos(){
       jfSubGrupo.setEnabled(true);
       jcbGrupo.setEnabled(true);
       jbNovo.setEnabled(false);
       jbInserir.setEnabled(true);
       jblimparCampos.setEnabled(true);
    
    }
    
    private void habilitarCamposAlteracao(){
       jfSubGrupo.setEnabled(true);
       jcbGrupo.setEnabled(true);
       jblimparCampos.setEnabled(true);
       jbAlterar.setEnabled(true);
       jbExcluir.setEnabled(true);
       
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jfCodigo = new javax.swing.JTextField();
      jfSubGrupo = new javax.swing.JTextField();
      jcbGrupo = new javax.swing.JComboBox();
      jbNovo = new javax.swing.JButton();
      jblimparCampos = new javax.swing.JButton();
      jbInserir = new javax.swing.JButton();
      jbAlterar = new javax.swing.JButton();
      jbExcluir = new javax.swing.JButton();
      jbPrimeiro = new javax.swing.JButton();
      jbAnterior = new javax.swing.JButton();
      jbProximo = new javax.swing.JButton();
      jbUltimo = new javax.swing.JButton();
      jbSair = new javax.swing.JButton();
      jPanel2 = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      jtSubGrupo = new javax.swing.JTable();
      jbChamaGrupo = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Formulário SubGrupos");
      setBackground(new java.awt.Color(255, 255, 255));

      jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jLabel2.setText("Código:");

      jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jLabel3.setText("Grupo:");

      jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jLabel4.setText("SubGrupo:");

      jfCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jfCodigo.setEnabled(false);

      jfSubGrupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jfSubGrupo.setEnabled(false);

      jcbGrupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jcbGrupo.setEnabled(false);

      jbNovo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      jbNovo.setText("Novo");
      jbNovo.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbNovoActionPerformed(evt);
         }
      });

      jblimparCampos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      jblimparCampos.setText("Limpar");
      jblimparCampos.setEnabled(false);
      jblimparCampos.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jblimparCamposActionPerformed(evt);
         }
      });

      jbInserir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      jbInserir.setText("Salvar");
      jbInserir.setEnabled(false);
      jbInserir.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbInserirActionPerformed(evt);
         }
      });

      jbAlterar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      jbAlterar.setText("Alterar");
      jbAlterar.setEnabled(false);
      jbAlterar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbAlterarActionPerformed(evt);
         }
      });

      jbExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      jbExcluir.setText("Excluir");
      jbExcluir.setEnabled(false);
      jbExcluir.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbExcluirActionPerformed(evt);
         }
      });

      jbPrimeiro.setText("<<");
      jbPrimeiro.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbPrimeiroActionPerformed(evt);
         }
      });

      jbAnterior.setText("<");
      jbAnterior.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbAnteriorActionPerformed(evt);
         }
      });

      jbProximo.setText(">");
      jbProximo.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbProximoActionPerformed(evt);
         }
      });

      jbUltimo.setText(">>");
      jbUltimo.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbUltimoActionPerformed(evt);
         }
      });

      jbSair.setText("Voltar ao Menu");
      jbSair.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbSairActionPerformed(evt);
         }
      });

      jPanel2.setBackground(java.awt.SystemColor.textHighlight);

      jtSubGrupo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
      jtSubGrupo.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {},
            {},
            {},
            {}
         },
         new String [] {

         }
      ));
      jtSubGrupo.setGridColor(new java.awt.Color(255, 255, 255));
      jScrollPane1.setViewportView(jtSubGrupo);

      org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
            .addContainerGap())
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 192, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(246, 246, 246))
      );

      jbChamaGrupo.setText("+");
      jbChamaGrupo.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbChamaGrupoActionPerformed(evt);
         }
      });

      org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
               .add(layout.createSequentialGroup()
                  .add(20, 20, 20)
                  .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                     .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                           .add(jLabel2)
                           .add(jLabel4)
                           .add(jLabel3))
                        .add(36, 36, 36)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                           .add(layout.createSequentialGroup()
                              .add(jbPrimeiro)
                              .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                              .add(jbAnterior)
                              .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                              .add(jbProximo)
                              .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                              .add(jbUltimo))
                           .add(layout.createSequentialGroup()
                              .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                 .add(layout.createSequentialGroup()
                                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                       .add(jcbGrupo, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                       .add(jfSubGrupo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 219, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jbChamaGrupo))
                                 .add(jfCodigo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                              .add(52, 52, 52)
                              .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                 .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(jblimparCampos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jbNovo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                 .add(jbSair)))))
                     .add(layout.createSequentialGroup()
                        .add(jbInserir)
                        .add(18, 18, 18)
                        .add(jbAlterar)
                        .add(18, 18, 18)
                        .add(jbExcluir))))
               .add(layout.createSequentialGroup()
                  .addContainerGap()
                  .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
            .add(30, 37, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
               .add(layout.createSequentialGroup()
                  .add(36, 36, 36)
                  .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                     .add(jLabel2)
                     .add(jfCodigo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                  .add(18, 18, 18)
                  .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                     .add(jcbGrupo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                     .add(jbChamaGrupo)
                     .add(jLabel3))
                  .add(18, 18, 18)
                  .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                     .add(jLabel4)
                     .add(jfSubGrupo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                  .add(32, 32, 32)
                  .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                     .add(jbInserir)
                     .add(jbAlterar)
                     .add(jbExcluir)))
               .add(layout.createSequentialGroup()
                  .add(41, 41, 41)
                  .add(jbNovo)
                  .add(18, 18, 18)
                  .add(jblimparCampos)
                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .add(jbSair)
                  .add(18, 18, 18)
                  .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                     .add(jbPrimeiro)
                     .add(jbAnterior)
                     .add(jbProximo)
                     .add(jbUltimo))))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 21, Short.MAX_VALUE)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 217, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );

      setSize(new java.awt.Dimension(599, 492));
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        dispose();
        FrmMenuPrincipal frmMenu = new FrmMenuPrincipal();
        frmMenu.setVisible(true);
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbChamaGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbChamaGrupoActionPerformed
       FrmGrupo chamaGrupo = new FrmGrupo();
       chamaGrupo.setVisible(true);
    }//GEN-LAST:event_jbChamaGrupoActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
       habilitarCampos();
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jblimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblimparCamposActionPerformed
       limparCampos();
    }//GEN-LAST:event_jblimparCamposActionPerformed

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
       if(jcbGrupo.getSelectedItem().equals("") || jfSubGrupo.getText().trim().isEmpty()){
          JOptionPane.showMessageDialog(null, "Preencha todos os campos");
       } else{
            
            try{
            
               connSubGrupo.conexao();
               connGrupo.conexao();
               connGrupo.executaaSQL("SELECT * FROM GRUPO_PRODUTO WHERE NOME_GRUPO = '" + jcbGrupo.getSelectedItem() + "'");
               connGrupo.rs.first();
               
               modSubGrupo.getGrupo().setCodigo(connGrupo.rs.getInt("CODIGO_GRUPO"));
               modSubGrupo.setNomeSubGrupo(jfSubGrupo.getText());
               
               controle.Inserir(modSubGrupo);
               
               preencherTabela();
               limparCampos();
            } catch(SQLException ex){
                 JOptionPane.showMessageDialog(null, "Erro ao setar e gravar registro:\n" + ex);
              }
            
            
            
         }

    }//GEN-LAST:event_jbInserirActionPerformed

    
    
    public void setaCampos(){
       jfCodigo.setText("" + modSubGrupo.getCodigo());
       jcbGrupo.setSelectedItem(modSubGrupo.getGrupo().getNomeGrupo());
       jfSubGrupo.setText(modSubGrupo.getNomeSubGrupo());
       
       habilitarCamposAlteracao();
    }
    private void jbPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrimeiroActionPerformed
       modSubGrupo = controle.Primeiro();
       
       setaCampos();
    }//GEN-LAST:event_jbPrimeiroActionPerformed

    private void jbAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnteriorActionPerformed
       modSubGrupo = controle.Anterior();
       
       setaCampos();
    }//GEN-LAST:event_jbAnteriorActionPerformed

    private void jbProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProximoActionPerformed
       modSubGrupo = controle.Proximo();
       
       setaCampos();
       
    }//GEN-LAST:event_jbProximoActionPerformed

    private void jbUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUltimoActionPerformed
       modSubGrupo = controle.Ultimo();
       
       setaCampos();
       
    }//GEN-LAST:event_jbUltimoActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
       if(jcbGrupo.getSelectedItem().equals("") || jfSubGrupo.getText().trim().isEmpty()){
          JOptionPane.showMessageDialog(null, "Preencha todos os campos");
       } else{
            
            try{
               connSubGrupo.conexao();
               connGrupo.conexao();
               connGrupo.executaaSQL("SELECT * FROM GRUPO_PRODUTO WHERE NOME_GRUPO = '" + jcbGrupo.getSelectedItem() + "'");
               connGrupo.rs.first();
               
               modSubGrupo.getGrupo().setCodigo(connGrupo.rs.getInt("CODIGO_GRUPO"));
               modSubGrupo.setNomeSubGrupo(jfSubGrupo.getText());
               
               controle.Alterar(modSubGrupo);
               preencherTabela();
               limparCampos();
            } catch(SQLException e){
                 JOptionPane.showMessageDialog(null, "Erro ao alterar registro:\n");
              }
       
       
       
         }
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
       if(jcbGrupo.getSelectedItem().equals("") || jfSubGrupo.getText().trim().isEmpty()){
          JOptionPane.showMessageDialog(null, "Preencha todos os campos");
       } else{
            
            try{
               connSubGrupo.conexao();
               connGrupo.conexao();
               connGrupo.executaaSQL("SELECT * FROM GRUPO_PRODUTO WHERE NOME_GRUPO = '" + jcbGrupo.getSelectedItem() + "'");
               connGrupo.rs.first();
               modSubGrupo.setCodigo(Integer.parseInt(jfCodigo.getText()));
               modSubGrupo.getGrupo().setCodigo(connGrupo.rs.getInt("CODIGO_GRUPO"));
               modSubGrupo.setNomeSubGrupo(jfSubGrupo.getText());
               
               controle.Excluir(modSubGrupo);
               preencherTabela();
               limparCampos();
            } catch(SQLException e){
                 JOptionPane.showMessageDialog(null, "Erro ao alterar registro:\n");
              }
         }
    }//GEN-LAST:event_jbExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSubGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSubGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSubGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSubGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSubGrupo().setVisible(true);
            }
        });
    }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JButton jbAlterar;
   private javax.swing.JButton jbAnterior;
   private javax.swing.JButton jbChamaGrupo;
   private javax.swing.JButton jbExcluir;
   private javax.swing.JButton jbInserir;
   private javax.swing.JButton jbNovo;
   private javax.swing.JButton jbPrimeiro;
   private javax.swing.JButton jbProximo;
   private javax.swing.JButton jbSair;
   private javax.swing.JButton jbUltimo;
   private javax.swing.JButton jblimparCampos;
   private javax.swing.JComboBox jcbGrupo;
   private javax.swing.JTextField jfCodigo;
   private javax.swing.JTextField jfSubGrupo;
   private javax.swing.JTable jtSubGrupo;
   // End of variables declaration//GEN-END:variables
}
