/*
 * @author Gustavo Mathias de Siqueira 
 * @date 01/05/2016 
 * 
 */

package visao;

import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import controle.ConexaoBanco;
import controle.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;



public class JDialogRecebimentosAbertos extends javax.swing.JDialog {
   public static FrmReceberCompra frmReceber;
   ConexaoBanco connReceb = new ConexaoBanco();
   
   
    /** Creates new form JDialogRecebimentosAbertos */
    public JDialogRecebimentosAbertos(FrmReceberCompra parent, boolean modal) {
        super(parent, modal);
        try {
          UIManager.setLookAndFeel(new WindowsLookAndFeel());
        } 
        catch (UnsupportedLookAndFeelException ex) {
           Logger.getLogger(FrmAvaliacaoDeCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
      
      this.frmReceber = parent;
      this.setModal(modal);
      initComponents();
      setLocationRelativeTo(this);
    }

    
    
    
    
   public void preencheTabela(){
      ArrayList dados = new ArrayList();
       
       String [] Colunas = new String[]{"Data","Recebimento", "Compra", "Nota Fiscal", "Serie", "Emissão"};
       
       
       try{
         
           connReceb.conexao();
           connReceb.executaaSQL("SELECT DATA_RECEBIMENTO, CODIGO_RECEBIMENTO, CODIGO_COMPRA, NOTA_FISCAL, SERIE_NF, DATA_EMISSAO FROM RECEBER_COMPRA WHERE STATUS = 'ABERTO' ORDER BY CODIGO_RECEBIMENTO ASC;");
           
           
           
          if(!connReceb.rs.first()){
             JOptionPane.showMessageDialog(null, "Nenhum recebimento aberto");
             
          } else{  
           
               do{
                  dados.add(new Object[]{
                     dataBR(connReceb.rs.getString("DATA_RECEBIMENTO")), connReceb.rs.getInt("CODIGO_RECEBIMENTO"),
                     connReceb.rs.getInt("CODIGO_COMPRA"), connReceb.rs.getString("NOTA_FISCAL"),
                     connReceb.rs.getString("SERIE_NF"), dataBR(connReceb.rs.getString("DATA_EMISSAO"))
                          
             
               });   
                
          
               } while(connReceb.rs.next());
            
            }
       } catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
         }
       
       ModeloTabela modelo = new ModeloTabela(dados, Colunas);
       
       jtReceb.setModel(modelo);
       jtReceb.getColumnModel().getColumn(0).setPreferredWidth(80);
       jtReceb.getColumnModel().getColumn(0).setResizable(true);
       
       jtReceb.getColumnModel().getColumn(1).setPreferredWidth(80);
       jtReceb.getColumnModel().getColumn(1).setResizable(true);
       
       jtReceb.getColumnModel().getColumn(2).setPreferredWidth(80);
       jtReceb.getColumnModel().getColumn(2).setResizable(true);
       
       jtReceb.getColumnModel().getColumn(3).setPreferredWidth(80);
       jtReceb.getColumnModel().getColumn(3).setResizable(true);
       
       jtReceb.getColumnModel().getColumn(4).setPreferredWidth(80);
       jtReceb.getColumnModel().getColumn(4).setResizable(true);
       
       jtReceb.getColumnModel().getColumn(5).setPreferredWidth(80);
       jtReceb.getColumnModel().getColumn(5).setResizable(true);
       
       jtReceb.getTableHeader().setReorderingAllowed(!true);
       jtReceb.setAutoResizeMode(jtReceb.AUTO_RESIZE_ALL_COLUMNS);//tamanho automatico conforme como é o layout
      
       jtReceb.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
   
   
   } 
    
    
    
    
    
    public String dataBR(String data){
       String dataBanco = data.substring(8,10) + "/" + data.substring(5,7) + "/" + data.substring(2,4);
       return dataBanco;
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      jtReceb = new javax.swing.JTable();
      jbCancelar = new javax.swing.JButton();
      jbEscolherReceb = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setResizable(false);

      jtReceb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      jtReceb.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {},
            {},
            {},
            {}
         },
         new String [] {

         }
      ));
      jtReceb.setGridColor(new java.awt.Color(255, 255, 255));
      jtReceb.setRowHeight(25);
      jScrollPane1.setViewportView(jtReceb);

      jbCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      jbCancelar.setText("Cancelar");
      jbCancelar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbCancelarActionPerformed(evt);
         }
      });

      jbEscolherReceb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
      jbEscolherReceb.setText("Confirmar");
      jbEscolherReceb.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbEscolherRecebActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jbEscolherReceb)
                  .addGap(18, 18, 18)
                  .addComponent(jbCancelar)
                  .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jbCancelar)
               .addComponent(jbEscolherReceb))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      setSize(new java.awt.Dimension(853, 384));
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
      dispose();
   }//GEN-LAST:event_jbCancelarActionPerformed

   private void jbEscolherRecebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEscolherRecebActionPerformed
      String codigo = String.valueOf(jtReceb.getValueAt(jtReceb.getSelectedRow(), 1));
      String data = String.valueOf(jtReceb.getValueAt(jtReceb.getSelectedRow(), 0));
      String compra = String.valueOf(jtReceb.getValueAt(jtReceb.getSelectedRow(), 2));
      String nf = String.valueOf(jtReceb.getValueAt(jtReceb.getSelectedRow(), 3));
      String serie = String.valueOf(jtReceb.getValueAt(jtReceb.getSelectedRow(), 4));
      String emissao = String.valueOf(jtReceb.getValueAt(jtReceb.getSelectedRow(), 5));
      
      frmReceber.defineDadosRecebimento(codigo, data, compra, nf, serie, emissao);
      frmReceber.liberaBotao(true);
      dispose();
   }//GEN-LAST:event_jbEscolherRecebActionPerformed

   
   
   
   
   
   
   
   
   
   
   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogRecebimentosAbertos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogRecebimentosAbertos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogRecebimentosAbertos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogRecebimentosAbertos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogRecebimentosAbertos dialog = new JDialogRecebimentosAbertos(frmReceber, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JButton jbCancelar;
   private javax.swing.JButton jbEscolherReceb;
   private javax.swing.JTable jtReceb;
   // End of variables declaration//GEN-END:variables

}
